settings:
  prefix: "#ffd8e0&l[#ffdadb&lS#ffdcd5&la#ffddd0&lt#ffdfcb&lc#ffdfcb&lh#ffddd0&le#ffdcd5&ll#ffdadb&ls#ffd8e0&l]"

satchels:
  stone:
    name: "&7Stone Satchel"
    lore:
      - "&7This Satchel picks up %satchel-target%"
      - ""
      - "#ffe0c8Capacity: #e0f0ff%satchel-contents% &7/ #e0f0ff%satchel-capacity%"
      - "#ffe0c8Sell Bonus: #e0f0ff%satchel-sellbonus%"
      - "#ffe0c8Value: #e0f0ff$%satchel-value%"
      - ""
    enchanted: true
    material: CHEST
    target: STONE
    default-capacity: 5
  blaze_rod:
    name: "&cBlaze Rod Satchel"
    lore:
      - "&7This Satchel picks up %satchel-target%"
      - ""
      - "#ffe0c8Capacity: #e0f0ff%satchel-contents% &7/ #e0f0ff%satchel-capacity%"
      - "#ffe0c8Sell Bonus: #e0f0ff%satchel-sellbonus%"
      - "#ffe0c8Value: #e0f0ff$%satchel-value%"
      - ""
    enchanted: true
    material: BLAZE_ROD
    target: BLAZE_ROD
    default-capacity: 10

messages:
  on-give:
    sender: "%prefix% #9CD5F2You have given %satchel% #9CD5F2to &f%player%!#9CD5F2"
    target:  "%prefix% #9CD5F2You have received a %satchel%#9CD5F2!"
  on-toggle:
    enable: "%prefix% #9CD5F2You have &a&nENABLED&r #9CD5F2your %satchel%#9CD5F2!"
    disable: "%prefix% #9CD5F2You have &c&nDISABLED&r #9CD5F2your %satchel%#9CD5F2!"
  on-conflict:
    full: "%prefix% #9CD5F2Your %satchel% #9CD5F2is &nFULL&r#9CD5F2!"
  on-sell:
    success: "%prefix% #9CD5F2You have sold &f%satchel-contents% items #9CD5F2and made &f$%satchel-value%#9CD5F2!"
    fail: "%prefix% #9CD5F2You have nothing to sell!"

menus:
  satchel:
    title: "%satchel-name%"
    size: 9
    buttons:
      information:
        name: "%satchel-item.name%"
        lore:
          - ""
          - "&d&l- &fContents: %satchel-contents% / %satchel-capacity%"
          - "&d&l- &fUpgrade: %satchel-capacity% &7&l» &f%satchel-capacity.next% &7(&fCost: $%satchel-capacity.next-price%&7)"
          - ""
          - "&7» &fClick To &e&nUpgrade&r &7«"
        enchanted: false
        material: "%satchel-item.material%"
        action: "UPGRADE"
        slot: 4
      collect:
        name: "&bCollect"
        lore:
          - "&7Click to collect an amount of items"
          - "&7from this satchel."
          - ""
          - "&7» &fClick To &b&nWithdraw&r &7«"
        enchanted: false
        material: PAPER
        action: "COLLECT"
        slot: 2
      sell:
        name: "&aSell"
        lore:
          - "&7Click to sell the collected contents"
          - "&7from this satchel."
          - ""
          - "&d&l- &fValue: &a$%satchel-value%"
          - ""
          - "&7» &fClick To &a&nSell&r &7«"
        enchanted: false
        material: EMERALD
        action: "SELL"
        slot: 6
