settings:
  prefix: "#ffd8e0&l[#ffdadb&lS#ffdcd5&la#ffddd0&lt#ffdfcb&lc#ffdfcb&lh#ffddd0&le#ffdcd5&ll#ffdadb&ls#ffd8e0&l]"
  value-hook: Satchels #Options: Satchels, ShopGUIPlus and EconomyShopGUI

satchels:
  stone:
    name: "&7Stone Satchel"
    lore:
      - "&7This Satchel picks up %satchel-target%"
      - ""
      - "#ffe0c8Capacity: #e0f0ff%satchel-contents% &7/ #e0f0ff%satchel-capacity%"
      - "#ffe0c8Value: #e0f0ff$%satchel-value% &7(#e0f0ffx%satchel-sellbonus%)&7"
      - ""
    enchanted: true
    material: CHEST
    target: STONE
    default-capacity: 5
    default-sellbonus: 1
  blaze_rod:
    name: "&cBlaze Rod Satchel"
    lore:
      - "&7This Satchel picks up %satchel-target%"
      - ""
      - "#ffe0c8Capacity: #e0f0ff%satchel-contents% &7/ #e0f0ff%satchel-capacity%"
      - "#ffe0c8Value: #e0f0ff$%satchel-value% &7(#e0f0ffx%satchel-sellbonus%)&7"
      - ""
    enchanted: true
    material: BLAZE_ROD
    target: BLAZE_ROD
    default-capacity: 10
    default-sellbonus: 1

messages:
  on-give:
    sender: "%prefix% #9CD5F2You have given %satchel% #9CD5F2to &f%player%!#9CD5F2"
    target:  "%prefix% #9CD5F2You have received a %satchel%#9CD5F2!"
  on-toggle:
    enable: "%prefix% #9CD5F2You have &a&nENABLED&r #9CD5F2your %satchel%#9CD5F2!"
    disable: "%prefix% #9CD5F2You have &c&nDISABLED&r #9CD5F2your %satchel%#9CD5F2!"
  on-conflict:
    full: "%prefix% #9CD5F2Your %satchel% #9CD5F2is &nFULL&r#9CD5F2!"
  on-sell:
    success: "%prefix% #9CD5F2You have sold &f%satchel-contents% items #9CD5F2and made &f$%satchel-value%#9CD5F2!"
    fail: "%prefix% #9CD5F2You have nothing to sell!"
  on-upgrade:
    success: "%prefix% #9CD5F2You have upgraded your &r%satchel%'s &f%value-type% %value-old% &7-> &f%value-new%#9CD5F2!"
    fail: "%prefix% #9CD5F2You do not have enough money for this upgrade!"

menus:
  satchel:
    title: "%satchel-name%"
    size: 9
    buttons:
      information:
        name: "%satchel-item.name%"
        lore:
          - ""
          - "&d&l- &fContents: %satchel-contents% / %satchel-capacity%"
          - ""
          - "&7» &fClick To View &e&nUpgrade&r &7«"
        enchanted: false
        material: "%satchel-item.material%"
        action: "OPEN_UPGRADES"
        slot: 4
      collect:
        name: "&bCollect"
        lore:
          - "&7Click to collect an amount of items"
          - "&7from this satchel."
          - ""
          - "&7» &fClick To &b&nCollect&r &7«"
        enchanted: false
        material: PAPER
        action: "COLLECT"
        slot: 2
      sell:
        name: "&aSell"
        lore:
          - "&7Click to sell the collected contents"
          - "&7from this satchel."
          - ""
          - "&d&l- &fValue: &a$%satchel-value%"
          - ""
          - "&7» &fClick To &a&nSell&r &7«"
        enchanted: false
        material: EMERALD
        action: "SELL"
        slot: 6
  collect:
    title: "%satchel-name%"
    size: 27
    buttons:
      confirm:
        name: "&aConfirm"
        lore:
          - "&8Click to collect from your Satchel!"
        material: LIME_WOOL
        slot: [0,1,2,9,10,11,18,19,20]
        action: "COLLECT_CONFIRM"
      item:
        name: "%satchel-item.name%"
        lore:
          - ""
          - "&7Contents: &f%satchel-contents%"
          - "&7Withdrawing: &f%amount%"
          - ""
        enchanted: false
        material: "%satchel-item.material%"
        slot: 13
        action: "INCREASE_AMOUNT"
      cancel:
        name: "&cCancel"
        lore:
          - "&8Click to cancel this collect request!"
        material: RED_WOOL
        slot: [6,7,8,15,16,17,24,25,26]
        action: "CLOSE_MENU"
  upgrade:
    title: "%satchel-name%"
    size: 9
    buttons:
      capacity:
        name: "&eCapacity"
        lore:
          - ""
          - "&d&l- &fCurrent Bonus: %satchel-capacity%"
          - "&d&l- &fNext Bonus: %satchel-capacity.next% &7(&fCost: $%satchel-capacity.next-price%&7)"
          - ""
          - "&7» &fClick To &e&nUpgrade&r &7«"
        material: CHEST
        enchanted: false
        action: "UPGRADE:CAPACITY"
        slot: 3
      sell-bonus:
        name: "&aSell Bonus"
        lore:
          - ""
          - "&d&l- &fCurrent Bonus: %satchel-sellbonus%"
          - "&d&l- &fNext Bonus: %satchel-sellbonus.next% &7(&fCost: $%satchel-sellbonus.next-price%&7)"
          - ""
          - "&7» &fClick To &a&nUpgrade&r &7«"
        material: DIAMOND
        enchanted: false
        action: "UPGRADE:SELLBONUS"
        slot: 5